### ISSUE TITLE
NtpCheck() doesn't work on non-English OS

### ISSUE THREAD

**Issue by devtdeng** [cloudfoundry-incubator/hakim#2]
The function checks return string other than return value, hence it only works on English OS. I confirmed it's not working on Chinese OS no matter ntp update works well. 

```
func NtpCheck() error {
	stdout, _, _ := RunCommand("w32tm /resync")
	if strings.Contains(stdout, "The command completed successfully") {
		return nil
	} else {
...
```

**Comment by sunjayBhatia** [comment]
@devtdeng we have a proposed fix here: https://github.com/cloudfoundry-incubator/hakim/pull/3
